export const START_SAVE_USER='START_SAVE_USER';
export const SAVE_USER_SUCCESS='SAVE_USER_SUCCESS';
export const SAVE_USER_FAILURE='SAVE_USER_FAILURE';
export const START_AUTH_USER='START_AUTH_USER';
export const AUTH_USER_SUCCESS='AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE='AUTH_USER_FAILURE';
export const START_VERIFY_EMAIL='START_VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS='VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE='VERIFY_EMAIL_FAILURE';
export const START_VERIFY_NICKNAME='START_VERIFY_NICKNAME';
export const VERIFY_NICKNAME_SUCCESS='VERIFY_NICKNAME_SUCCESS';
export const VERIFY_NICKNAME_FAILURE='VERIFY_NICKNAME_FAILURE';
export const LOGOUT_USER='LOGOUT_USER';
export const LOGOUT_USER_SUCCESS='LOGOUT_USER_SUCCESS';



