export const START_SAVE_USER='START_SAVE_USER';
export const SAVE_USER_SUCCESS='SAVE_USER_SUCCESS';
export const SAVE_USER_FAILURE='SAVE_USER_FAILURE';
export const START_AUTH_USER='START_AUTH_USER';
export const AUTH_USER_SUCCESS='AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE='AUTH_USER_FAILURE';
export const LOGOUT_USER='LOGOUT_USER';



