export const START_SAVE_USER='START_SAVE_USER';
export const SAVE_USER_SUCCESS='SAVE_USER_SUCCESS';
export const SAVE_USER_FAILURE='SAVE_USER_FAILURE';
export const START_AUTH_USER='START_AUTH_USER';
export const AUTH_USER_SUCCESS='AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE='AUTH_USER_FAILURE';
export const START_VERIFY_EMAIL='START_VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS='VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE='VERIFY_EMAIL_FAILURE';
export const START_VERIFY_NICKNAME='START_VERIFY_NICKNAME';
export const VERIFY_NICKNAME_SUCCESS='VERIFY_NICKNAME_SUCCESS';
export const VERIFY_NICKNAME_FAILURE='VERIFY_NICKNAME_FAILURE';
export const LOGOUT_USER='LOGOUT_USER';
export const LOGOUT_USER_SUCCESS='LOGOUT_USER_SUCCESS';
export const START_GET_MAKES='START_GET_MAKES';
export const GET_MAKES_SUCCESS='GET_MAKES_SUCCESS';
export const GET_MAKES_FAILURE='GET_MAKES_FAILURE';
export const START_GET_MODELS='START_GET_MODELS';
export const GET_MODELS_SUCCESS='GET_MODELS_SUCCESS';
export const GET_MODELS_FAILURE='GET_MODELS_FAILURE';
export const START_SAVE_AD='START_SAVE_AD';
export const SAVE_AD_SUCCESS='SAVE_AD_SUCCESS';
export const SAVE_AD_FAILURE='SAVE_AD_FAILURE';



